### ISSUE TITLE
Support for multiple select

### ISSUE THREAD

**Issue by Seldaek** [jefersondaniel/dom-form-serializer#1]
Thanks for the great lib, it's actually working wonders compared to a few others I looked at.

My only gripe here is the lack of support for `<select>` tags with `multiple` enabled.

Basically in that case it should return an array of values instead of just reading the element.value field, which returns the first one only. It can be done by iterating over all the `<option>` tags to find the ones with `selected == true`. I looked a bit at the code but couldn't easily figure out how to add it myself so I report it instead. If you'd rather have a PR please give some pointers and I'm happy to get the rest done.

**Comment by jefersondaniel** [comment]
Hi, thanks for the feedback. It should be working now.
