### ISSUE TITLE
Clarify difference to native FormData method

### ISSUE THREAD

**Issue by HaNdTriX** [jefersondaniel/dom-form-serializer#13]
Nowadays we have `FormData` and `Object.fromEntries` to do the same natively.

```js
const form = document.querySelector('#form')
const formData = new FormData(form)
const jsonData = Object.fromEntries(formData)
```

Does it make sence to explain in the readme, when to use what?

- https://caniuse.com/?search=formdata 
- https://caniuse.com/?search=Object.fromEntries

**Comment by jefersondaniel** [comment]
The fromEntries approach does not give the same results depending on the input types. The documentation shows some examples of how the input types are handled.
