### ISSUE TITLE
when the npm update?

### ISSUE THREAD

**Issue by terranc** [jefersondaniel/dom-form-serializer#4]
The current version can't support array Inputs.

**Comment by jefersondaniel** [comment]
Can you give a example of the problem? The version 1.0.5 work with select multiple

https://www.webpackbin.com/bins/-KzkMAu56gCNzbcqQr0Q

**Comment by terranc** [comment]
The version 1.0.5 of README.md doesn't see `array Inputs`.
![image](https://user-images.githubusercontent.com/224353/33228321-4e8f5334-d1f3-11e7-96ae-61f02cde92e4.png)

example：
https://www.webpackbin.com/bins/-Kzm-wOFpy4STp4LGKjZ

This result is different from the description in README。

**Comment by jefersondaniel** [comment]
Version 1.0.7 fix this bug, see https://www.webpackbin.com/bins/-L-EJae0DUe2rOyZ2iCQ

**Comment by terranc** [comment]
thanks
