### ISSUE TITLE
input[submit] vs docs

### ISSUE THREAD

**Issue by goofballLogic** [jefersondaniel/dom-form-serializer#5]
The README says you can explicitly include `input type=submit` and others like `button`, but the code bails out before inspecting the "include" option: https://github.com/jefersondaniel/dom-form-serializer/blob/master/lib/getInputElements.js#L8

**Comment by jefersondaniel** [comment]
The behavior of button value submission is normally dependent of which button was clicked. I changed the docs to avoid confusions. But you could make a PR adding this behavior without break compatibility if you want.

https://html.com/attributes/button-value
