### ISSUE TITLE
Custom splitters not working

### ISSUE THREAD

**Issue by yongaru** [jefersondaniel/dom-form-serializer#6]
![image](https://user-images.githubusercontent.com/9762549/48376979-dd696e00-e70f-11e8-80e1-556c7d0fad21.png)

**Comment by yongaru** [comment]
* this work fine
````js
 var data = serialize(document.querySelector(`#form`), { keySplitter: function(key){
        return key.split(".")
 }})
````

**Comment by jefersondaniel** [comment]
Hi, could you give a not working example? This option only accepts a function

**Comment by jefersondaniel** [comment]
The documentation was wrong. Only functions are accepted in key splitter.
